version: '3.8'

services:
  nats:
    image: nats:2.10-alpine
    container_name: tapio-nats
    ports:
      - "4222:4222"  # Client port
      - "8222:8222"  # HTTP monitoring port
      - "6222:6222"  # Cluster port
    command: |
      -js                    # Enable JetStream
      -sd /data              # Storage directory
      -m 8222                # Enable monitoring
      -DV                    # Debug and verbose logging
    volumes:
      - ./data/nats:/data
    networks:
      - tapio-net

  nats-box:
    image: natsio/nats-box:latest
    container_name: tapio-nats-box
    networks:
      - tapio-net
    command: sleep infinity

networks:
  tapio-net:
    driver: bridge