# ==========================================
# Tapio golangci-lint Configuration v2.x
# ==========================================

# Version is required for golangci-lint v2
version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - ebpf
  modules-download-mode: readonly

linters:
  enable:
    # Essential linters only - no formatters
    - errcheck          # Check for unchecked errors
    - gosimple          # Simplify code
    - govet             # Go vet examination
    - ineffassign       # Detect ineffectual assignments
    - staticcheck       # Go static analysis
    - unused            # Check for unused constants, variables, functions and types

# ==========================================
# Issues Configuration
# ==========================================
issues:
  # Set to 0 to disable limit
  max-issues-per-linter: 50
  max-same-issues: 3

  # Show only new issues if `revive` is enabled
  new: false

  # Fix found issues (if it's supported by the linter)
  fix: false