run:
  timeout: 10m
  tests: true
  skip-dirs:
    - vendor
    - bin
    - dist

linters-settings:
  govet:
    check-shadowing: true
    fieldalignment: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/falseyair/tapio
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
  revive:
    confidence: 0.8
  staticcheck:
    checks: ["all"]

linters:
  enable:
    - bodyclose
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace
    - revive
    - exportloopref
    - nilerr

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - funlen
    - path: cmd/
      linters:
        - gocyclo
  max-issues-per-linter: 0
  max-same-issues: 0