# ==========================================
# Tapio golangci-lint Configuration v2.x
# ==========================================

# Version is required for golangci-lint v2
version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - ebpf
  exclude-dirs:
    - vendor
    - bin
    - dist
    - build
    - .git
    - pkg/mod
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"
  modules-download-mode: readonly

linters-settings:
  # Go vet configuration
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - shadow # Too noisy for some codebases
      - fieldalignment # Can be too strict

  # Cyclomatic complexity
  gocyclo:
    min-complexity: 15

  # Duplicate code detection
  dupl:
    threshold: 100

  # Constants detection
  goconst:
    min-len: 2
    min-occurrences: 3
    ignore-tests: true

  # Misspelling
  misspell:
    locale: US
    ignore-words:
      - tapio
      - ebpf
      - kubernetes

  # Line length
  lll:
    line-length: 120
    tab-width: 4

  # Imports formatting
  goimports:
    local-prefixes: github.com/yairfalse/tapio

  # Security linting
  gosec:
    excludes:
      - G114  # Use of net/http serve function that has no support for setting timeouts
      - G204  # Subprocess launched with variable (for testing)
    confidence: medium
    severity: medium

  # Code critic
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - dupImport
      - ifElseChain
      - hugeParam
      - rangeValCopy

  # Error handling
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)

  # Function complexity
  funlen:
    lines: 100
    statements: 50

  # Cognitive complexity
  gocognit:
    min-complexity: 30

  # Maintainability index
  revive:
    confidence: 0.8
    rules:
      - name: exported
        disabled: false
        arguments:
          - checkPrivateReceivers
          - sayRepetitiveInsteadOfStutter
      - name: unreachable-code
      - name: unused-parameter
      - name: var-naming
      - name: package-comments
        disabled: true # Too noisy for some packages
      - name: indent-error-flow
      - name: if-return
      - name: empty-block
      - name: superfluous-else
      - name: confusing-naming
      - name: get-return
      - name: modifies-parameter
      - name: confusing-results
      - name: deep-exit
      - name: flag-parameter
      - name: unnecessary-stmt
      - name: struct-tag
      - name: modifies-value-receiver
      - name: constant-logical-expr
      - name: bool-literal-in-expr
      - name: redefines-builtin-id
      - name: imports-blacklist
      - name: range-val-in-closure
      - name: range-val-address
      - name: waitgroup-by-value
      - name: atomic
      - name: empty-lines
      - name: call-to-gc
      - name: duplicated-imports
      - name: import-shadowing
      - name: bare-return
      - name: unused-receiver
      - name: unhandled-error
      - name: cognitive-complexity
        arguments: [25]

  # Static analysis
  staticcheck:
    checks: ["all"]

  # Unused variables
  unused:
    check-exported: false

  # Nil analysis
  nilnil:
    checked-types:
      - ptr
      - func
      - iface
      - map
      - chan

  # Performance linters
  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  # Code style
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: true
    require-specific: true

  # Test naming
  testpackage:
    skip-regexp: '(export|internal)_test\.go'

  # Variable naming
  varnamelen:
    min-name-length: 1
    ignore-names:
      - err
      - id
      - ip
      - ok
      - wg
      - mu
      - db
      - fs
      - ts
    ignore-decls:
      - c echo.Context
      - t testing.T
      - f *foo.Bar
      - e error
      - i int

  # TAPIO ARCHITECTURE ENFORCEMENT - Critical for 5-level hierarchy
  depguard:
    rules:
      prevent-domain-violations:
        files:
          - "pkg/domain/**/*.go"
        deny:
          - pkg: "github.com/yairfalse/tapio/pkg/collectors"
            desc: "domain layer cannot import collectors (violates hierarchy)"
          - pkg: "github.com/yairfalse/tapio/pkg/intelligence"
            desc: "domain layer cannot import intelligence (violates hierarchy)"
          - pkg: "github.com/yairfalse/tapio/pkg/integrations"
            desc: "domain layer cannot import integrations (violates hierarchy)"
          - pkg: "github.com/yairfalse/tapio/pkg/interfaces"
            desc: "domain layer cannot import interfaces (violates hierarchy)"
      
      prevent-collector-cross-imports:
        files:
          - "pkg/collectors/**/*.go"
        deny:
          - pkg: "github.com/yairfalse/tapio/pkg/collectors/ebpf"
            desc: "collectors cannot import other collectors (violates isolation)"
          - pkg: "github.com/yairfalse/tapio/pkg/collectors/k8s"
            desc: "collectors cannot import other collectors (violates isolation)"
          - pkg: "github.com/yairfalse/tapio/pkg/collectors/systemd"
            desc: "collectors cannot import other collectors (violates isolation)"
          - pkg: "github.com/yairfalse/tapio/pkg/collectors/journald"
            desc: "collectors cannot import other collectors (violates isolation)"
          - pkg: "github.com/yairfalse/tapio/pkg/intelligence"
            desc: "collectors cannot import intelligence layer (violates hierarchy)"
          - pkg: "github.com/yairfalse/tapio/pkg/integrations"
            desc: "collectors cannot import integrations layer (violates hierarchy)"
          - pkg: "github.com/yairfalse/tapio/pkg/interfaces"
            desc: "collectors cannot import interfaces layer (violates hierarchy)"
      
      prevent-intelligence-violations:
        files:
          - "pkg/intelligence/**/*.go"
        deny:
          - pkg: "github.com/yairfalse/tapio/pkg/integrations"
            desc: "intelligence cannot import integrations layer (violates hierarchy)"
          - pkg: "github.com/yairfalse/tapio/pkg/interfaces"
            desc: "intelligence cannot import interfaces layer (violates hierarchy)"

  # Import aliases for consistency
  importas:
    no-unaliased: true
    alias:
      - pkg: "context"
        alias: "ctx"
      - pkg: "github.com/yairfalse/tapio/pkg/domain"
        alias: "domain"
      - pkg: "k8s.io/api/core/v1"
        alias: "corev1"
      - pkg: "k8s.io/apimachinery/pkg/apis/meta/v1"
        alias: "metav1"

# ==========================================
# Enabled Linters
# ==========================================
linters:
  enable-all: false
  enable:
    # Essential linters
    - errcheck          # Check for unchecked errors
    - gosimple          # Simplify code
    - govet             # Go vet examination
    - ineffassign       # Detect ineffectual assignments
    - staticcheck       # Go static analysis
    - unused            # Check for unused constants, variables, functions and types

    # Code quality
    - gofmt             # Check whether code was gofmt-ed
    - goimports         # Check import formatting
    - revive            # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - misspell          # Finds commonly misspelled English words in comments
    - unconvert         # Remove unnecessary type conversions
    - whitespace        # Tool for detection of leading and trailing whitespace

    # Performance
    - prealloc          # Find slice declarations that could potentially be preallocated
    
    # Security
    - gosec             # Inspects source code for security problems

    # Style
    - gocyclo           # Computes and checks the cyclomatic complexity of functions
    - funlen            # Tool for detection of long functions
    - gocognit          # Computes and checks the cognitive complexity of functions
    - lll               # Reports long lines
    - nakedret          # Finds naked returns in functions greater than a specified function length

    # Bugs
    - bodyclose         # Checks whether HTTP response body is closed successfully
    - nilerr            # Finds the code that returns nil even if it checks that the error is not nil
    - noctx             # Find sending http request without context.Context
    - sqlclosecheck     # Checks that sql.Rows and sql.Stmt are closed

    # Advanced
    - gocritic          # Provides diagnostics that check for bugs, performance and style issues
    - nilnil            # Checks that there is no simultaneous return of nil error and an invalid value

    # Architecture enforcement (CRITICAL for Tapio)
    - depguard          # Enforces 5-level hierarchy and prevents cross-imports
    - importas          # Enforces consistent import aliases

    # Test quality
    - testpackage       # Makes you use a separate _test package

# ==========================================
# Issues Configuration
# ==========================================
issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - gocognit
        - lll

    # Exclude some linters from running on main/cmd files
    - path: cmd/
      linters:
        - gocyclo
        - funlen
        - gocognit

    # Exclude some linters from running on generated files
    - path: ".*\\.pb\\.go"
      linters:
        - gocyclo
        - dupl
        - gosec
        - funlen

    # Exclude some linters for eBPF-related files (can be noisy)
    - path: pkg/collectors/ebpf/
      linters:
        - gosec  # eBPF code often needs unsafe operations

    # Exclude from legacy files during migration
    - path: ".*\\.go\\.disabled"
      linters:
        - gocyclo
        - dupl
        - gosec

  # Specific text exclusions
  exclude:
    - "should have a package comment"
    - "don't use ALL_CAPS in Go names"

  # Set to 0 to disable limit
  max-issues-per-linter: 50
  max-same-issues: 3

  # Show only new issues if `revive` is enabled
  new: false

  # Fix found issues (if it's supported by the linter)
  fix: false

# ==========================================
# Output Configuration
# ==========================================
output:
  format: colored-line-number