codecov:
  require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: "60...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 5%
        base: auto
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
        
    patch:
      default:
        target: 60%
        threshold: 10%
        base: auto
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "**/*_test.go"
  - "**/mock_*.go"
  - "test/**"
  - "vendor/**"
  - "*.pb.go"
  - "cmd/tapio/main.go"