version: '3.8'

services:
  neo4j:
    image: neo4j:5-community
    container_name: tapio-neo4j
    ports:
      - "7474:7474"  # Browser
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_server_memory_heap_max__size=1G
      - NEO4J_server_memory_heap_initial__size=512M
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  neo4j_data:
  neo4j_logs: