apiVersion: v1
kind: ServiceAccount
metadata:
  name: tapio-collector
  namespace: tapio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tapio-collector
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
  - cronjobs
  - jobs
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tapio-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tapio-collector
subjects:
- kind: ServiceAccount
  name: tapio-collector
  namespace: tapio-system