# DNS Collector Metrics Configuration
# Monitors DNS queries, responses, and performance

collector: "dns"
version: "1.0.0"

defaults:
  export:
    prometheus:
      enabled: true
      namespace: "tapio"
      subsystem: "dns"
    opentelemetry:
      enabled: true
      meter_name: "tapio.dns"
      version: "1.0.0"
  performance:
    sample_rate: 1.0
    collect_every: "5s"
    cache_metrics: true
    batch_size: 200
  labels:
    collector: "dns"
    node: "${NODE_NAME:-unknown}"

# Decoder definitions for DNS-specific data
decoders:
  dns_qtype:
    type: "enum"
    description: "DNS query types"
    config:
      values:
        "1": "A"
        "2": "NS"
        "5": "CNAME"
        "6": "SOA"
        "12": "PTR"
        "15": "MX"
        "16": "TXT"
        "28": "AAAA"
        "33": "SRV"
        "255": "ANY"
      default: "UNKNOWN"

  dns_rcode:
    type: "enum"
    description: "DNS response codes"
    config:
      values:
        "0": "NOERROR"
        "1": "FORMERR"
        "2": "SERVFAIL"
        "3": "NXDOMAIN"
        "4": "NOTIMP"
        "5": "REFUSED"
        "6": "YXDOMAIN"
        "7": "YXRRSET"
        "8": "NXRRSET"
        "9": "NOTAUTH"
        "10": "NOTZONE"
      default: "UNKNOWN"

  dns_flags:
    type: "flags"
    description: "DNS message flags"
    config:
      flags:
        "0x0100": "RD"     # Recursion Desired
        "0x0080": "RA"     # Recursion Available
        "0x0400": "AD"     # Authentic Data
        "0x0010": "CD"     # Checking Disabled
        "0x8000": "QR"     # Query Response

  source_ip:
    type: "ip"
    description: "Source IP address"
    config:
      format: "decimal"

  dest_ip:
    type: "ip"
    description: "Destination IP address"
    config:
      format: "decimal"

  k8s_pod:
    type: "k8s"
    description: "Kubernetes pod resolver"
    config:
      resource: "pod"
      field: "name"

# Metric definitions
metrics:
  # DNS Query Metrics
  - name: "queries_total"
    type: "counter"
    help: "Total number of DNS queries"
    table: "dns_queries"
    value_field: "count"
    labels:
      - "qtype"
      - "qname"
      - "source_pod"
      - "source_namespace"
    label_fields:
      qtype:
        field: "query_type"
        decoder:
          type: "dns_qtype"
      qname:
        field: "query_name"
        default: "unknown"
      source_pod:
        field: "source_ip"
        decoder:
          type: "k8s_pod"
        default: "unknown"
      source_namespace:
        field: "source_namespace"
        default: "unknown"

  - name: "responses_total"
    type: "counter"
    help: "Total number of DNS responses"
    table: "dns_responses"
    value_field: "count"
    labels:
      - "rcode"
      - "qtype"
      - "authoritative"
      - "cached"
    label_fields:
      rcode:
        field: "response_code"
        decoder:
          type: "dns_rcode"
      qtype:
        field: "query_type"
        decoder:
          type: "dns_qtype"
      authoritative:
        field: "authoritative"
        decoder:
          type: "enum"
          config:
            values:
              "0": "false"
              "1": "true"
            default: "unknown"
      cached:
        field: "from_cache"
        decoder:
          type: "enum"
          config:
            values:
              "0": "false"
              "1": "true"
            default: "unknown"

  - name: "query_duration_seconds"
    type: "histogram"
    help: "DNS query resolution time in seconds"
    table: "dns_latency"
    value_field: "duration_us"
    labels:
      - "qtype"
      - "rcode"
      - "server"
    label_fields:
      qtype:
        field: "query_type"
        decoder:
          type: "dns_qtype"
      rcode:
        field: "response_code"
        decoder:
          type: "dns_rcode"
      server:
        field: "server_ip"
        decoder:
          type: "dest_ip"
        default: "unknown"
    histogram:
      strategy: "exp2"
      min: 0.0001   # 100Î¼s
      max: 5.0      # 5s
      count: 20
    performance:
      sample_rate: 0.5  # Sample 50% for performance

  # DNS Error Metrics
  - name: "errors_total"
    type: "counter"
    help: "Total DNS errors"
    table: "dns_errors"
    value_field: "error_count"
    labels:
      - "error_type"
      - "qtype"
      - "server"
    label_fields:
      error_type:
        field: "error_type"
        decoder:
          type: "enum"
          config:
            values:
              "1": "timeout"
              "2": "network_unreachable"
              "3": "connection_refused"
              "4": "malformed_response"
              "5": "truncated_response"
            default: "unknown"
      qtype:
        field: "query_type"
        decoder:
          type: "dns_qtype"
      server:
        field: "server_ip"
        decoder:
          type: "dest_ip"

  # DNS Cache Metrics
  - name: "cache_hits_total"
    type: "counter"
    help: "Total DNS cache hits"
    table: "dns_cache"
    value_field: "hit_count"
    labels:
      - "qtype"
      - "cache_type"
    label_fields:
      qtype:
        field: "query_type"
        decoder:
          type: "dns_qtype"
      cache_type:
        field: "cache_type"
        decoder:
          type: "enum"
          config:
            values:
              "1": "positive"
              "2": "negative"
              "3": "nxdomain"
            default: "unknown"

  - name: "cache_misses_total"
    type: "counter"
    help: "Total DNS cache misses"
    table: "dns_cache"
    value_field: "miss_count"
    labels:
      - "qtype"
      - "reason"
    label_fields:
      qtype:
        field: "query_type"
        decoder:
          type: "dns_qtype"
      reason:
        field: "miss_reason"
        decoder:
          type: "enum"
          config:
            values:
              "1": "not_cached"
              "2": "expired"
              "3": "invalidated"
            default: "unknown"

  # DNS Server Performance
  - name: "server_response_time_seconds"
    type: "histogram"
    help: "DNS server response time distribution"
    table: "server_performance"
    value_field: "response_time_us"
    labels:
      - "server"
      - "protocol"
    label_fields:
      server:
        field: "server_ip"
        decoder:
          type: "dest_ip"
      protocol:
        field: "protocol"
        decoder:
          type: "enum"
          config:
            values:
              "17": "UDP"
              "6": "TCP"
              "853": "DoT"  # DNS over TLS
              "443": "DoH"  # DNS over HTTPS
            default: "UDP"
    histogram:
      strategy: "fixed"
      buckets: [0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0]

  - name: "active_queries"
    type: "gauge"
    help: "Number of active DNS queries"
    table: "query_tracker"
    value_field: "active_count"
    const_labels:
      metric_type: "active_queries"

  # Top Queried Domains
  - name: "top_domains_queries_total"
    type: "counter"
    help: "Queries to frequently accessed domains"
    table: "top_domains"
    value_field: "query_count"
    labels:
      - "domain"
      - "category"
    label_fields:
      domain:
        field: "domain_name"
        default: "unknown"
      category:
        field: "domain_category"
        decoder:
          type: "static_map"
          config:
            mapping:
              "kubernetes.default.svc.cluster.local": "k8s_service"
              "svc.cluster.local": "k8s_service"
              "amazonaws.com": "cloud_provider"
              "googleapis.com": "cloud_provider"
              "azure.com": "cloud_provider"
            default: "external"
    performance:
      max_entries: 100  # Only track top 100 domains

# Resource limits
limits:
  max_metrics: 2000
  max_label_values: 20000
  max_memory_mb: 150
  collection_timeout: "30s"