# ETCD Collector Metrics Configuration
# Monitors etcd key-value operations, performance, and cluster health

collector: "etcd"
version: "1.0.0"

defaults:
  export:
    prometheus:
      enabled: true
      namespace: "tapio"
      subsystem: "etcd"
    opentelemetry:
      enabled: true
      meter_name: "tapio.etcd"
      version: "1.0.0"
  performance:
    sample_rate: 1.0
    collect_every: "5s"
    cache_metrics: true
    batch_size: 150
  labels:
    collector: "etcd"
    node: "${NODE_NAME:-unknown}"
    etcd_cluster: "${ETCD_CLUSTER_NAME:-default}"

# Decoder definitions for etcd-specific data
decoders:
  etcd_operation:
    type: "enum"
    description: "ETCD operation types"
    config:
      values:
        "1": "PUT"
        "2": "GET"
        "3": "DELETE"
        "4": "WATCH"
        "5": "LEASE_GRANT"
        "6": "LEASE_REVOKE"
        "7": "LEASE_RENEW"
        "8": "COMPACT"
        "9": "RANGE"
        "10": "TXN"
        "11": "MEMBER_ADD"
        "12": "MEMBER_REMOVE"
        "13": "MEMBER_UPDATE"
      default: "unknown"

  etcd_result:
    type: "enum"
    description: "ETCD operation results"
    config:
      values:
        "0": "success"
        "1": "key_not_found"
        "2": "compare_failed"
        "3": "too_many_ops"
        "4": "duplicate_key"
        "5": "compacted"
        "6": "future_revision"
        "7": "no_space"
        "8": "key_exists"
        "9": "value_provided"
        "10": "lease_not_found"
        "11": "lease_exist"
        "12": "member_exist"
        "13": "peer_url_exist"
        "14": "member_not_enough"
        "15": "member_bad_urls"
        "16": "cluster_version_unavailable"
        "17": "wrong_leader"
      default: "error"

  watch_event_type:
    type: "enum"
    description: "Watch event types"
    config:
      values:
        "0": "PUT"
        "1": "DELETE"
      default: "unknown"

  key_namespace:
    type: "static_map"
    description: "Kubernetes key namespace mapping"
    config:
      mapping:
        "/registry/pods": "pods"
        "/registry/services": "services"
        "/registry/configmaps": "configmaps"
        "/registry/secrets": "secrets"
        "/registry/deployments": "deployments"
        "/registry/replicasets": "replicasets"
        "/registry/nodes": "nodes"
        "/registry/namespaces": "namespaces"
        "/registry/events": "events"
        "/registry/leases": "leases"
        "/registry/ingresses": "ingresses"
        "/registry/persistentvolumes": "persistentvolumes"
        "/registry/persistentvolumeclaims": "persistentvolumeclaims"
        "/registry/storageclasses": "storageclasses"
        "/registry/clusterroles": "clusterroles"
        "/registry/clusterrolebindings": "clusterrolebindings"
        "/registry/roles": "roles"
        "/registry/rolebindings": "rolebindings"
        "/registry/serviceaccounts": "serviceaccounts"
      default: "other"

  error_codes:
    type: "errno"
    description: "System error codes"

# Metric definitions
metrics:
  # ETCD Operation Metrics
  - name: "operations_total"
    type: "counter"
    help: "Total number of etcd operations"
    table: "etcd_operations"
    value_field: "count"
    labels:
      - "operation"
      - "result"
      - "key_namespace"
      - "client_type"
    label_fields:
      operation:
        field: "operation_type"
        decoder:
          type: "etcd_operation"
      result:
        field: "result_code"
        decoder:
          type: "etcd_result"
      key_namespace:
        field: "key_prefix"
        decoder:
          type: "key_namespace"
      client_type:
        field: "client_type"
        decoder:
          type: "enum"
          config:
            values:
              "1": "kube_apiserver"
              "2": "kube_controller"
              "3": "kube_scheduler"
              "4": "kubelet"
              "5": "etcd_operator"
              "6": "external_client"
            default: "unknown"

  - name: "operation_duration_seconds"
    type: "histogram"
    help: "Duration of etcd operations in seconds"
    table: "etcd_latency"
    value_field: "duration_us"
    labels:
      - "operation"
      - "result"
      - "key_namespace"
    label_fields:
      operation:
        field: "operation_type"
        decoder:
          type: "etcd_operation"
      result:
        field: "result_code"
        decoder:
          type: "etcd_result"
      key_namespace:
        field: "key_prefix"
        decoder:
          type: "key_namespace"
    histogram:
      strategy: "exp2"
      min: 0.0001   # 100Î¼s
      max: 30.0     # 30s
      count: 20

  # Key-Value Store Metrics
  - name: "key_operations_total"
    type: "counter"
    help: "Total key operations by namespace"
    table: "key_stats"
    value_field: "operation_count"
    labels:
      - "namespace"
      - "operation"
      - "key_type"
    label_fields:
      namespace:
        field: "key_prefix"
        decoder:
          type: "key_namespace"
      operation:
        field: "operation_type"
        decoder:
          type: "etcd_operation"
      key_type:
        field: "key_type"
        decoder:
          type: "enum"
          config:
            values:
              "1": "single_key"
              "2": "prefix_range"
              "3": "all_keys"
            default: "unknown"

  - name: "key_size_bytes"
    type: "histogram"
    help: "Size distribution of keys and values"
    table: "key_sizes"
    value_field: "size_bytes"
    labels:
      - "data_type"
      - "namespace"
    label_fields:
      data_type:
        field: "data_type"
        decoder:
          type: "enum"
          config:
            values:
              "1": "key"
              "2": "value"
            default: "unknown"
      namespace:
        field: "key_prefix"
        decoder:
          type: "key_namespace"
    histogram:
      strategy: "exp2"
      min: 1        # 1 byte
      max: 1048576  # 1MB
      count: 20

  # Watch Metrics
  - name: "watch_events_total"
    type: "counter"
    help: "Total watch events"
    table: "watch_events"
    value_field: "event_count"
    labels:
      - "event_type"
      - "namespace"
      - "watcher_type"
    label_fields:
      event_type:
        field: "event_type"
        decoder:
          type: "watch_event_type"
      namespace:
        field: "key_prefix"
        decoder:
          type: "key_namespace"
      watcher_type:
        field: "watcher_type"
        decoder:
          type: "enum"
          config:
            values:
              "1": "kube_apiserver"
              "2": "controller"
              "3": "custom_controller"
            default: "unknown"

  - name: "active_watchers"
    type: "gauge"
    help: "Number of active watchers"
    table: "watcher_stats"
    value_field: "active_count"
    labels:
      - "namespace"
      - "watcher_type"
    label_fields:
      namespace:
        field: "key_prefix"
        decoder:
          type: "key_namespace"
      watcher_type:
        field: "watcher_type"
        decoder:
          type: "enum"
          config:
            values:
              "1": "kube_apiserver"
              "2": "controller"
              "3": "custom_controller"
            default: "unknown"

  # Lease Metrics
  - name: "lease_operations_total"
    type: "counter"
    help: "Total lease operations"
    table: "lease_events"
    value_field: "count"
    labels:
      - "operation"
      - "result"
      - "lease_type"
    label_fields:
      operation:
        field: "operation_type"
        decoder:
          type: "enum"
          config:
            values:
              "1": "grant"
              "2": "revoke"
              "3": "renew"
              "4": "timetolive"
            default: "unknown"
      result:
        field: "result_code"
        decoder:
          type: "etcd_result"
      lease_type:
        field: "lease_type"
        decoder:
          type: "enum"
          config:
            values:
              "1": "leader_election"
              "2": "coordination"
              "3": "session"
              "4": "heartbeat"
            default: "unknown"

  - name: "active_leases"
    type: "gauge"
    help: "Number of active leases"
    table: "lease_stats"
    value_field: "active_count"
    labels:
      - "lease_type"
      - "ttl_range"
    label_fields:
      lease_type:
        field: "lease_type"
        decoder:
          type: "enum"
          config:
            values:
              "1": "leader_election"
              "2": "coordination"
              "3": "session"
              "4": "heartbeat"
            default: "unknown"
      ttl_range:
        field: "ttl_seconds"
        decoder:
          type: "enum"
          config:
            values:
              "0": "short"    # < 30s
              "1": "medium"   # 30s - 300s
              "2": "long"     # > 300s
            default: "unknown"

  # Transaction Metrics
  - name: "transactions_total"
    type: "counter"
    help: "Total transactions executed"
    table: "transaction_events"
    value_field: "count"
    labels:
      - "result"
      - "operations_count"
      - "namespace"
    label_fields:
      result:
        field: "result_code"
        decoder:
          type: "etcd_result"
      operations_count:
        field: "op_count"
        decoder:
          type: "enum"
          config:
            values:
              "1": "single"
              "2": "few"      # 2-5 ops
              "3": "many"     # 6+ ops
            default: "unknown"
      namespace:
        field: "key_prefix"
        decoder:
          type: "key_namespace"

  # Compaction Metrics
  - name: "compactions_total"
    type: "counter"
    help: "Total compaction operations"
    table: "compaction_events"
    value_field: "count"
    labels:
      - "type"
      - "result"
    label_fields:
      type:
        field: "compaction_type"
        decoder:
          type: "enum"
          config:
            values:
              "1": "periodic"
              "2": "manual"
              "3": "auto"
            default: "unknown"
      result:
        field: "result_code"
        decoder:
          type: "etcd_result"

  - name: "compaction_duration_seconds"
    type: "histogram"
    help: "Compaction operation duration"
    table: "compaction_duration"
    value_field: "duration_ms"
    labels:
      - "type"
    label_fields:
      type:
        field: "compaction_type"
        decoder:
          type: "enum"
          config:
            values:
              "1": "periodic"
              "2": "manual"
              "3": "auto"
            default: "unknown"
    histogram:
      strategy: "exp2"
      min: 0.1      # 100ms
      max: 3600.0   # 1 hour
      count: 15

  # Cluster Health Metrics
  - name: "cluster_health"
    type: "gauge"
    help: "Cluster health status (1=healthy, 0=unhealthy)"
    table: "cluster_health"
    value_field: "health_status"
    labels:
      - "member_id"
      - "health_check"
    label_fields:
      member_id:
        field: "member_id"
        format: "%.8s"  # First 8 chars of member ID
      health_check:
        field: "check_type"
        decoder:
          type: "enum"
          config:
            values:
              "1": "connectivity"
              "2": "raft_health"
              "3": "db_size"
              "4": "leader_election"
            default: "unknown"

  # Error Metrics
  - name: "errors_total"
    type: "counter"
    help: "Total etcd errors"
    table: "etcd_errors"
    value_field: "error_count"
    labels:
      - "error_type"
      - "operation"
      - "severity"
    label_fields:
      error_type:
        field: "error_type"
        decoder:
          type: "enum"
          config:
            values:
              "1": "raft_timeout"
              "2": "leader_lost"
              "3": "network_partition"
              "4": "disk_full"
              "5": "corrupt_data"
              "6": "auth_failed"
              "7": "rate_limited"
            default: "unknown"
      operation:
        field: "operation_type"
        decoder:
          type: "etcd_operation"
      severity:
        field: "severity"
        decoder:
          type: "enum"
          config:
            values:
              "1": "low"
              "2": "medium"
              "3": "high"
              "4": "critical"
            default: "unknown"

  # Performance Metrics
  - name: "disk_sync_duration_seconds"
    type: "histogram"
    help: "Disk sync operation duration"
    table: "disk_sync"
    value_field: "sync_duration_us"
    const_labels:
      operation: "fsync"
    histogram:
      strategy: "exp2"
      min: 0.001    # 1ms
      max: 1.0      # 1s
      count: 15

  - name: "network_roundtrip_duration_seconds"
    type: "histogram"
    help: "Network round-trip time between etcd members"
    table: "network_latency"
    value_field: "rtt_us"
    labels:
      - "target_member"
    label_fields:
      target_member:
        field: "target_member_id"
        format: "%.8s"
    histogram:
      strategy: "linear"
      min: 0.001    # 1ms
      max: 0.1      # 100ms
      count: 20

# Resource limits
limits:
  max_metrics: 2000
  max_label_values: 25000
  max_memory_mb: 200
  collection_timeout: "45s"