# CNI Collector Metrics Configuration
# Monitors container network interface operations and traffic

collector: "cni"
version: "1.0.0"

defaults:
  export:
    prometheus:
      enabled: true
      namespace: "tapio"
      subsystem: "cni"
    opentelemetry:
      enabled: true
      meter_name: "tapio.cni"
      version: "1.0.0"
  performance:
    sample_rate: 1.0
    collect_every: "5s"
    cache_metrics: true
    batch_size: 100
  labels:
    collector: "cni"
    node: "${NODE_NAME:-unknown}"

# Decoder definitions for CNI-specific data
decoders:
  cni_operation:
    type: "enum"
    description: "CNI operation types"
    config:
      values:
        "0": "ADD"
        "1": "DEL"
        "2": "CHECK"
        "3": "VERSION"
      default: "UNKNOWN"

  network_namespace:
    type: "static_map"
    description: "Network namespace to container mapping"
    config:
      mapping:
        # These would be populated dynamically
        default: "unknown"

  cni_result:
    type: "enum"
    description: "CNI operation results"
    config:
      values:
        "0": "SUCCESS"
        "1": "FAILURE"
        "2": "TIMEOUT"
      default: "UNKNOWN"

  ip_address:
    type: "ip"
    description: "IP address decoder"
    config:
      format: "decimal"

# Metric definitions
metrics:
  # CNI Operation Metrics
  - name: "operations_total"
    type: "counter"
    help: "Total number of CNI operations"
    table: "cni_operations"
    value_field: "count"
    labels:
      - "operation"
      - "plugin"
      - "result"
      - "namespace"
    label_fields:
      operation:
        field: "operation_type"
        decoder:
          type: "cni_operation"
      plugin:
        field: "plugin_name"
        default: "unknown"
      result:
        field: "result_code"
        decoder:
          type: "cni_result"
      namespace:
        field: "net_namespace"
        decoder:
          type: "network_namespace"

  - name: "operation_duration_seconds"
    type: "histogram"
    help: "Duration of CNI operations in seconds"
    table: "cni_durations"
    value_field: "duration_ns"
    labels:
      - "operation"
      - "plugin"
      - "result"
    label_fields:
      operation:
        field: "operation_type"
        decoder:
          type: "cni_operation"
      plugin:
        field: "plugin_name"
        default: "unknown"
      result:
        field: "result_code"
        decoder:
          type: "cni_result"
    histogram:
      strategy: "exp2"
      min: 0.001    # 1ms
      max: 10.0     # 10s
      count: 15
    performance:
      sample_rate: 0.1  # Sample 10% for performance

  # Network Traffic Metrics
  - name: "network_bytes_total"
    type: "counter"
    help: "Total bytes transferred by container networks"
    table: "network_stats"
    value_field: "bytes"
    labels:
      - "direction"
      - "interface"
      - "pod_name"
      - "namespace"
      - "container_id"
    label_fields:
      direction:
        field: "direction"
        decoder:
          type: "enum"
          config:
            values:
              "0": "ingress"
              "1": "egress"
            default: "unknown"
      interface:
        field: "interface_name"
        default: "unknown"
      pod_name:
        field: "pod_name"
        default: "unknown"
      namespace:
        field: "pod_namespace"
        default: "default"
      container_id:
        field: "container_id"
        format: "%.12s"  # First 12 chars of container ID

  - name: "network_packets_total"
    type: "counter"
    help: "Total packets transferred by container networks"
    table: "network_stats"
    value_field: "packets"
    labels:
      - "direction"
      - "interface"
      - "pod_name"
      - "namespace"
    label_fields:
      direction:
        field: "direction"
        decoder:
          type: "enum"
          config:
            values:
              "0": "ingress"
              "1": "egress"
            default: "unknown"
      interface:
        field: "interface_name"
        default: "unknown"
      pod_name:
        field: "pod_name"
        default: "unknown"
      namespace:
        field: "pod_namespace"
        default: "default"

  # CNI Plugin Errors
  - name: "plugin_errors_total"
    type: "counter"
    help: "Total CNI plugin errors"
    table: "cni_errors"
    value_field: "error_count"
    labels:
      - "plugin"
      - "error_type"
      - "operation"
    label_fields:
      plugin:
        field: "plugin_name"
        default: "unknown"
      error_type:
        field: "error_type"
        decoder:
          type: "enum"
          config:
            values:
              "1": "timeout"
              "2": "config_error"
              "3": "network_error"
              "4": "plugin_crash"
            default: "unknown"
      operation:
        field: "operation_type"
        decoder:
          type: "cni_operation"

  # Network Namespace Metrics
  - name: "namespaces_active"
    type: "gauge"
    help: "Number of active network namespaces"
    table: "namespace_stats"
    value_field: "active_count"
    const_labels:
      metric_type: "namespace_count"

  - name: "interface_status"
    type: "gauge"
    help: "Network interface status (1=up, 0=down)"
    table: "interface_states"
    value_field: "status"
    labels:
      - "interface"
      - "namespace"
      - "type"
    label_fields:
      interface:
        field: "interface_name"
        default: "unknown"
      namespace:
        field: "net_namespace"
        default: "unknown"
      type:
        field: "interface_type"
        decoder:
          type: "enum"
          config:
            values:
              "1": "veth"
              "2": "bridge"
              "3": "macvlan"
              "4": "ipvlan"
            default: "unknown"

# Resource limits
limits:
  max_metrics: 1000
  max_label_values: 10000
  max_memory_mb: 100
  collection_timeout: "30s"