# Tapio CLI Configuration
log_level: info

# Engine connection
engine:
  endpoint: "tapio-engine:9090"
  timeout: 30s
  tls: false

# CLI settings
cli:
  output_format: human
  color_output: true
  debug: false
  
# Kubernetes settings
kubernetes:
  kubeconfig: ""  # Use in-cluster config or default kubeconfig
  namespace: ""   # Use current context namespace
  
# Cache settings
cache:
  enabled: true
  ttl: 5m
  max_size: 100