// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadKernelmonitor returns the embedded CollectionSpec for kernelmonitor.
func loadKernelmonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KernelmonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load kernelmonitor: %w", err)
	}

	return spec, err
}

// loadKernelmonitorObjects loads kernelmonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*kernelmonitorObjects
//	*kernelmonitorPrograms
//	*kernelmonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadKernelmonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadKernelmonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// kernelmonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kernelmonitorSpecs struct {
	kernelmonitorProgramSpecs
	kernelmonitorMapSpecs
}

// kernelmonitorSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kernelmonitorProgramSpecs struct {
	TraceOpenat *ebpf.ProgramSpec `ebpf:"trace_openat"`
}

// kernelmonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kernelmonitorMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// kernelmonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadKernelmonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type kernelmonitorObjects struct {
	kernelmonitorPrograms
	kernelmonitorMaps
}

func (o *kernelmonitorObjects) Close() error {
	return _KernelmonitorClose(
		&o.kernelmonitorPrograms,
		&o.kernelmonitorMaps,
	)
}

// kernelmonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadKernelmonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type kernelmonitorMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *kernelmonitorMaps) Close() error {
	return _KernelmonitorClose(
		m.Events,
	)
}

// kernelmonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadKernelmonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type kernelmonitorPrograms struct {
	TraceOpenat *ebpf.Program `ebpf:"trace_openat"`
}

func (p *kernelmonitorPrograms) Close() error {
	return _KernelmonitorClose(
		p.TraceOpenat,
	)
}

func _KernelmonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed kernelmonitor_bpfel_x86.o
var _KernelmonitorBytes []byte
