apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dns-observer
  namespace: tapio-system
  labels:
    app: dns-observer
    component: observability
    part-of: tapio
spec:
  selector:
    matchLabels:
      app: dns-observer
  template:
    metadata:
      labels:
        app: dns-observer
        component: observability
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      serviceAccountName: dns-observer
      hostNetwork: true  # Required for eBPF network observation
      hostPID: true      # Required for process visibility
      containers:
      - name: dns-observer
        image: tapio/dns-observer:latest
        imagePullPolicy: IfNotPresent
        command:
        - /dns-observer-linux
        args:
        - --log-level=info
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        securityContext:
          privileged: true  # Required for eBPF
          capabilities:
            add:
            - SYS_ADMIN     # eBPF program loading
            - NET_ADMIN     # XDP attachment
            - SYS_RESOURCE  # Increase memlock limit
            - IPC_LOCK      # Lock memory for eBPF maps
        volumeMounts:
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: debugfs
          mountPath: /sys/kernel/debug
          readOnly: true
        - name: bpffs
          mountPath: /sys/fs/bpf
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: sys
        hostPath:
          path: /sys
      - name: debugfs
        hostPath:
          path: /sys/kernel/debug
      - name: bpffs
        hostPath:
          path: /sys/fs/bpf
      - name: localtime
        hostPath:
          path: /etc/localtime
      tolerations:
      # Run on all nodes including master
      - operator: Exists
      priorityClassName: system-node-critical
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns-observer
  namespace: tapio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-observer
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dns-observer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dns-observer
subjects:
- kind: ServiceAccount
  name: dns-observer
  namespace: tapio-system