---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config-template
  namespace: tapio
data:
  nats.conf.template: |
    # pid_file: "/var/run/nats/nats.pid"  # Not needed in container
    http: 8222

    # Client connections
    server_name: $HOSTNAME
    listen: 0.0.0.0:4222

    # Clustering
    cluster {
      name: "tapio-nats"
      listen: 0.0.0.0:6222
      routes = [
        nats://nats-0.nats-headless.tapio.svc.cluster.local:6222
        nats://nats-1.nats-headless.tapio.svc.cluster.local:6222
        nats://nats-2.nats-headless.tapio.svc.cluster.local:6222
      ]
      cluster_advertise: "__POD_NAME__.nats-headless.tapio.svc.cluster.local"
      connect_retries: 10
    }

    # JetStream configuration
    jetstream {
      store_dir: /data
      max_memory_store: 1Gi
      max_file_store: 10Gi
    }

    # Monitoring
    monitor_port: 8222
    
    # System limits
    max_connections: 10000
    max_subscriptions: 1000000
    max_payload: 8MB
    
    # Write deadline
    write_deadline: "30s"

  setup.sh: |
    #!/bin/sh
    sed "s/__POD_NAME__/$POD_NAME/g" /etc/nats-config-template/nats.conf.template > /etc/nats-config/nats.conf
    echo "Generated NATS config for pod: $POD_NAME"
    cat /etc/nats-config/nats.conf

---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: tapio
  labels:
    app: nats
spec:
  selector:
    app: nats
  clusterIP: None
  ports:
  - name: client
    port: 4222
  - name: cluster
    port: 6222
  - name: monitor
    port: 8222

---
apiVersion: v1
kind: Service
metadata:
  name: nats-headless
  namespace: tapio
  labels:
    app: nats
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: nats
  ports:
  - name: client
    port: 4222
  - name: cluster
    port: 6222
  - name: monitor
    port: 8222

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  namespace: tapio
  labels:
    app: nats
spec:
  selector:
    matchLabels:
      app: nats
  replicas: 3
  serviceName: nats-headless
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: nats
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: config-setup
        image: busybox:1.35
        command: ["/bin/sh", "/scripts/setup.sh"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: config-template
          mountPath: /etc/nats-config-template
        - name: config-volume
          mountPath: /etc/nats-config
        - name: scripts
          mountPath: /scripts
      containers:
      - name: nats
        image: nats:2.10-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor
        command:
        - nats-server
        - --config
        - /etc/nats-config/nats.conf
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nats-config
        - name: data
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
      volumes:
      - name: config-template
        configMap:
          name: nats-config-template
      - name: config-volume
        emptyDir: {}
      - name: scripts
        configMap:
          name: nats-config-template
          defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi