---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tapio-collector
  namespace: tapio-system
  labels:
    app.kubernetes.io/name: tapio-collector
    app.kubernetes.io/component: collector
    app.kubernetes.io/part-of: tapio
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tapio-collector
  labels:
    app.kubernetes.io/name: tapio-collector
    app.kubernetes.io/component: collector
    app.kubernetes.io/part-of: tapio
rules:
# Node access for eBPF and system information
- apiGroups: [""]
  resources:
    - nodes
    - nodes/proxy
    - nodes/metrics
    - nodes/stats
  verbs: ["get", "list", "watch"]

# Pod and container inspection
- apiGroups: [""]
  resources:
    - pods
    - pods/log
    - pods/status
    - containers
  verbs: ["get", "list", "watch"]

# Service and endpoint discovery
- apiGroups: [""]
  resources:
    - services
    - endpoints
    - endpointslices
  verbs: ["get", "list", "watch"]

# Namespace and configuration access
- apiGroups: [""]
  resources:
    - namespaces
    - configmaps
    - secrets
  verbs: ["get", "list", "watch"]

# Workload inspection
- apiGroups: ["apps"]
  resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
  verbs: ["get", "list", "watch"]

- apiGroups: ["batch"]
  resources:
    - jobs
    - cronjobs
  verbs: ["get", "list", "watch"]

# Network policy inspection
- apiGroups: ["networking.k8s.io"]
  resources:
    - networkpolicies
  verbs: ["get", "list", "watch"]

# Storage inspection
- apiGroups: ["storage.k8s.io"]
  resources:
    - storageclasses
  verbs: ["get", "list", "watch"]

- apiGroups: [""]
  resources:
    - persistentvolumes
    - persistentvolumeclaims
  verbs: ["get", "list", "watch"]

# RBAC inspection
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
    - roles
    - rolebindings
    - clusterroles
    - clusterrolebindings
  verbs: ["get", "list", "watch"]

# Custom resource inspection
- apiGroups: ["apiextensions.k8s.io"]
  resources:
    - customresourcedefinitions
  verbs: ["get", "list", "watch"]

# Events access
- apiGroups: [""]
  resources:
    - events
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tapio-collector
  labels:
    app.kubernetes.io/name: tapio-collector
    app.kubernetes.io/component: collector
    app.kubernetes.io/part-of: tapio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tapio-collector
subjects:
- kind: ServiceAccount
  name: tapio-collector
  namespace: tapio-system
---
# ServiceAccount for OTEL Collector
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tapio-otel-collector
  namespace: tapio-system
  labels:
    app.kubernetes.io/name: tapio-otel-collector
    app.kubernetes.io/component: otel-collector
    app.kubernetes.io/part-of: tapio
automountServiceAccountToken: true
---
# ClusterRole for OTEL Collector k8s attributes processor
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tapio-otel-collector
  labels:
    app.kubernetes.io/name: tapio-otel-collector
    app.kubernetes.io/component: otel-collector
    app.kubernetes.io/part-of: tapio
rules:
# Required for k8sattributes processor
- apiGroups: [""]
  resources:
    - pods
    - namespaces
    - nodes
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources:
    - replicasets
    - deployments
    - daemonsets
    - statefulsets
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions"]
  resources:
    - replicasets
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tapio-otel-collector
  labels:
    app.kubernetes.io/name: tapio-otel-collector
    app.kubernetes.io/component: otel-collector
    app.kubernetes.io/part-of: tapio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tapio-otel-collector
subjects:
- kind: ServiceAccount
  name: tapio-otel-collector
  namespace: tapio-system
---
# Additional ServiceAccount for high-privilege eBPF operations
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tapio-ebpf-privileged
  namespace: tapio-system
  labels:
    app.kubernetes.io/name: tapio-ebpf-privileged
    app.kubernetes.io/component: ebpf-collector
    app.kubernetes.io/part-of: tapio
automountServiceAccountToken: true
---
# Specialized role for eBPF operations requiring additional privileges
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tapio-ebpf-privileged
  labels:
    app.kubernetes.io/name: tapio-ebpf-privileged
    app.kubernetes.io/component: ebpf-collector
    app.kubernetes.io/part-of: tapio
rules:
# All permissions from standard collector
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
# Additional permissions for security event correlation
- apiGroups: ["policy"]
  resources:
    - podsecuritypolicies
    - poddisruptionbudgets
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tapio-ebpf-privileged
  labels:
    app.kubernetes.io/name: tapio-ebpf-privileged
    app.kubernetes.io/component: ebpf-collector
    app.kubernetes.io/part-of: tapio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tapio-ebpf-privileged
subjects:
- kind: ServiceAccount
  name: tapio-ebpf-privileged
  namespace: tapio-system