apiVersion: apps/v1
kind: Deployment
metadata:
  name: correlation-subscriber
  namespace: tapio-system
  labels:
    app: correlation-subscriber
    component: intelligence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: correlation-subscriber
  template:
    metadata:
      labels:
        app: correlation-subscriber
        component: intelligence
    spec:
      serviceAccountName: correlation-subscriber
      containers:
      - name: subscriber
        image: tapio-correlation-subscriber:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NATS_URL
          value: "nats://nats.tapio-system.svc.cluster.local:4222"
        - name: STREAM_NAME
          value: "TRACES"
        - name: SUBSCRIBER_NAME
          value: "k8s-correlation"
        - name: CORRELATION_WINDOW
          value: "5s"
        - name: MIN_EVENTS_FOR_CORR
          value: "2"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: correlation-subscriber
  namespace: tapio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: correlation-subscriber
rules:
# Read pods for K8s context enrichment
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
# Read services for network correlation
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
# Read configmaps/secrets (metadata only) for mount correlation
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
# Read nodes for spatial correlation
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: correlation-subscriber
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: correlation-subscriber
subjects:
- kind: ServiceAccount
  name: correlation-subscriber
  namespace: tapio-system