apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tapio.fullname" . }}-config
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "tapio.labels" . | nindent 4 }}
data:
  tapio.yaml: |
    # Tapio configuration
    updateInterval: {{ .Values.config.updateInterval }}
    
    # Memory thresholds
    memoryThresholds:
      warning: {{ .Values.config.memoryThresholds.warning }}
      critical: {{ .Values.config.memoryThresholds.critical }}
    
    # OOM prediction settings
    prediction:
      enabled: {{ .Values.config.prediction.enabled }}
      minConfidence: {{ .Values.config.prediction.minConfidence }}
      timeWindow: {{ .Values.config.prediction.timeWindow }}
    
    # Logging configuration
    logging:
      level: {{ .Values.config.logging.level }}
      format: {{ .Values.config.logging.format }}
    
    # Namespace filtering
    namespaces:
      {{- if .Values.config.namespaces.include }}
      include:
        {{- toYaml .Values.config.namespaces.include | nindent 8 }}
      {{- end }}
      {{- if .Values.config.namespaces.exclude }}
      exclude:
        {{- toYaml .Values.config.namespaces.exclude | nindent 8 }}
      {{- end }}
    
    # Server configuration (for node agents)
    server:
      address: {{ include "tapio.fullname" . }}-server:{{ .Values.server.service.port }}
    
    # Metrics configuration
    {{- if .Values.server.metrics.enabled }}
    metrics:
      enabled: true
      port: {{ .Values.server.metrics.port }}
      path: {{ .Values.server.metrics.path }}
    {{- end }}
    
    # Enterprise features
    {{- if .Values.enterprise.highAvailability.enabled }}
    highAvailability:
      enabled: true
      minReplicas: {{ .Values.enterprise.highAvailability.minReplicas }}
    {{- end }}
    
    {{- if .Values.enterprise.federation.enabled }}
    federation:
      enabled: true
      clusterId: {{ .Values.enterprise.federation.clusterId | quote }}
    {{- end }}
    
    {{- if .Values.enterprise.monitoring.tracing.enabled }}
    tracing:
      enabled: true
      endpoint: {{ .Values.enterprise.monitoring.tracing.endpoint | quote }}
    {{- end }}