// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyFix(arg1, arg2) {
  return window['go']['main']['App']['ApplyFix'](arg1, arg2);
}

export function ConnectToServer(arg1) {
  return window['go']['main']['App']['ConnectToServer'](arg1);
}

export function GetClusterStatus() {
  return window['go']['main']['App']['GetClusterStatus']();
}

export function GetServerInfo() {
  return window['go']['main']['App']['GetServerInfo']();
}

export function GetStories() {
  return window['go']['main']['App']['GetStories']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RefreshStories() {
  return window['go']['main']['App']['RefreshStories']();
}
