// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyFix(arg1:string,arg2:string):Promise<boolean>;

export function ConnectToServer(arg1:string):Promise<boolean>;

export function GetClusterStatus():Promise<main.ClusterStatus>;

export function GetServerInfo():Promise<Record<string, any>>;

export function GetStories():Promise<Array<main.Story>>;

export function Greet(arg1:string):Promise<string>;

export function RefreshStories():Promise<void>;
