# Update for collectors to use relay instead of direct engine connection
# This can be applied as a patch to existing collector DaemonSet
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tapio-collector
  namespace: tapio-system
spec:
  template:
    spec:
      containers:
      - name: collector
        env:
        # Change from direct engine connection to relay
        - name: TAPIO_COLLECTOR_SERVER
          value: "tapio-relay-headless:9095"  # Use headless service for better distribution
        # Add relay-specific configuration
        - name: TAPIO_COLLECTOR_USE_RELAY
          value: "true"
        - name: TAPIO_COLLECTOR_BATCH_SIZE
          value: "100"  # Smaller batches for relay aggregation
        - name: TAPIO_COLLECTOR_FLUSH_INTERVAL
          value: "500ms"  # More frequent flushes to relay