---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: tapio
data:
  nats.conf: |
    pid_file: "/var/run/nats/nats.pid"
    http: 8222

    # Client connections
    server_name: $HOSTNAME
    listen: 0.0.0.0:4222

    # Clustering
    cluster {
      name: "tapio-nats"
      listen: 0.0.0.0:6222
      routes = [
        nats://nats-0.nats-headless.tapio.svc.cluster.local:6222
        nats://nats-1.nats-headless.tapio.svc.cluster.local:6222
        nats://nats-2.nats-headless.tapio.svc.cluster.local:6222
      ]
      cluster_advertise: $CLUSTER_ADVERTISE
      connect_retries: 10
    }

    # JetStream configuration
    jetstream {
      store_dir: /data
      max_memory_store: 1Gi
      max_file_store: 10Gi
    }

    # Monitoring
    monitor_port: 8222
    
    # System limits
    max_connections: 10000
    max_subscriptions: 1000000
    max_payload: 8MB
    
    # Write deadline
    write_deadline: "30s"

---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: tapio
  labels:
    app: nats
spec:
  selector:
    app: nats
  clusterIP: None
  ports:
  - name: client
    port: 4222
  - name: cluster
    port: 6222
  - name: monitor
    port: 8222

---
apiVersion: v1
kind: Service
metadata:
  name: nats-headless
  namespace: tapio
  labels:
    app: nats
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: nats
  ports:
  - name: client
    port: 4222
  - name: cluster
    port: 6222
  - name: monitor
    port: 8222

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  namespace: tapio
  labels:
    app: nats
spec:
  selector:
    matchLabels:
      app: nats
  replicas: 3
  serviceName: nats-headless
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: nats
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: nats
        image: nats:2.10-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor
        env:
        - name: CLUSTER_ADVERTISE
          value: "$(POD_NAME).nats-headless.tapio.svc.cluster.local"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command:
        - nats-server
        - --config
        - /etc/nats-config/nats.conf
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nats-config
        - name: data
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
      volumes:
      - name: config-volume
        configMap:
          name: nats-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-stream-config
  namespace: tapio
data:
  setup-streams.sh: |
    #!/bin/sh
    set -e
    
    # Wait for NATS to be ready
    echo "Waiting for NATS to be ready..."
    sleep 10
    
    # Create raw events stream
    nats stream add RAW_EVENTS \
      --subjects="raw.*" \
      --retention=time \
      --max-age=24h \
      --storage=file \
      --replicas=3 \
      --discard=old \
      --max-msgs=-1 \
      --max-msgs-per-subject=-1 \
      --max-bytes=-1 \
      --max-msg-size=-1 \
      --dupe-window=2m \
      --no-ack \
      --defaults
    
    # Create unified events stream
    nats stream add UNIFIED_EVENTS \
      --subjects="unified.*" \
      --retention=time \
      --max-age=24h \
      --storage=file \
      --replicas=3 \
      --discard=old \
      --max-msgs=-1 \
      --max-msgs-per-subject=-1 \
      --max-bytes=-1 \
      --max-msg-size=-1 \
      --dupe-window=2m \
      --no-ack \
      --defaults
    
    echo "Streams created successfully"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: nats-stream-setup
  namespace: tapio
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: stream-setup
        image: natsio/nats-box:latest
        command: ["/bin/sh"]
        args: ["/scripts/setup-streams.sh"]
        env:
        - name: NATS_URL
          value: "nats://nats.tapio.svc.cluster.local:4222"
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: nats-stream-config
          defaultMode: 0755