---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: transformer
  namespace: tapio

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: transformer-config
  namespace: tapio
data:
  config.yaml: |
    service:
      name: transformer
      version: v1.0.0
    
    nats:
      url: nats://nats.tapio.svc.cluster.local:4222
      consumer:
        stream: RAW_EVENTS
        subject: "raw.>"
        durable: transformer-consumer
        max_ack_pending: 1000
        ack_wait: 30s
      
    logging:
      level: info
      format: json
    
    metrics:
      enabled: true
      port: 9090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transformer
  namespace: tapio
  labels:
    app: transformer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transformer
  template:
    metadata:
      labels:
        app: transformer
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: transformer
      containers:
      - name: transformer
        image: tapio/transformer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          name: metrics
        env:
        - name: NATS_URL
          value: "nats://nats.tapio.svc.cluster.local:4222"
        - name: LOG_LEVEL
          value: "info"
        - name: GOMAXPROCS
          value: "2"
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: config
        configMap:
          name: transformer-config

---
apiVersion: v1
kind: Service
metadata:
  name: transformer-metrics
  namespace: tapio
  labels:
    app: transformer
spec:
  selector:
    app: transformer
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: transformer-pdb
  namespace: tapio
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: transformer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: transformer-hpa
  namespace: tapio
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transformer
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60