apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: tapio
build:
  artifacts:
  - image: tapio-server
    context: .
    docker:
      dockerfile: cmd/tapio-server/Dockerfile
  - image: tapio-collector
    context: .
    docker:
      dockerfile: cmd/tapio-collector/Dockerfile
  local:
    push: false  # Don't push to registry for local dev
manifests:
  rawYaml:
  - deploy/k8s/namespace.yaml
  - deploy/k8s/*.yaml
  - deployments/nats/*.yaml
portForward:
- resourceType: service
  resourceName: tapio-server
  namespace: tapio-system
  port: 8080
  localPort: 8080  # REST API
- resourceType: service
  resourceName: tapio-server
  namespace: tapio-system  
  port: 9090
  localPort: 9090  # gRPC
- resourceType: service
  resourceName: jaeger-query
  namespace: tapio-system
  port: 16686
  localPort: 16686  # Jaeger UI
- resourceType: service
  resourceName: nats
  namespace: tapio-system
  port: 4222
  localPort: 4222  # NATS client
- resourceType: service
  resourceName: nats
  namespace: tapio-system
  port: 8222
  localPort: 8222  # NATS monitoring