#!/bin/bash

# Example script to test the connected API endpoints with correlation engine

API_BASE="http://localhost:8888/api/v1"

echo "Testing Tapio API Endpoints Connected to Correlation Engine"
echo "==========================================================="

# 1. Check server health
echo -e "\n1. Checking server health..."
curl -s "${API_BASE}/../health" | jq '.'

# 2. Check readiness (correlation engine initialized)
echo -e "\n2. Checking readiness..."
curl -s "${API_BASE}/../ready" | jq '.'

# 3. Get cluster health
echo -e "\n3. Getting cluster health..."
curl -s "${API_BASE}/health/cluster" | jq '.'

# 4. List all insights (from correlation engine)
echo -e "\n4. Listing all insights generated by correlation engine..."
curl -s "${API_BASE}/insights" | jq '.'

# 5. Get insights for specific resource
echo -e "\n5. Getting insights for api-deployment..."
curl -s "${API_BASE}/insights/production/api-deployment" | jq '.'

# 6. List active predictions
echo -e "\n6. Listing active predictions..."
curl -s "${API_BASE}/predictions" | jq '.'

# 7. Get predictions for specific resource
echo -e "\n7. Getting predictions for api-deployment..."
curl -s "${API_BASE}/predictions/production/api-deployment" | jq '.'

# 8. Get available fixes
echo -e "\n8. Getting available fixes for api-deployment..."
curl -s "${API_BASE}/fixes/production/api-deployment" | jq '.'

# 9. List correlation patterns
echo -e "\n9. Listing correlation patterns..."
curl -s "${API_BASE}/patterns?active=true" | jq '.'

# 10. Get network flows
echo -e "\n10. Getting network flows..."
curl -s "${API_BASE}/flows?protocol=http&limit=5" | jq '.'

# 11. Get L7 protocol flows
echo -e "\n11. Getting HTTP L7 flows..."
curl -s "${API_BASE}/flows/l7/http" | jq '.'

# 12. Get admin metrics (shows correlation engine stats)
echo -e "\n12. Getting admin metrics..."
curl -s "${API_BASE}/../admin/metrics" | jq '.'

# 13. Test correlation query
echo -e "\n13. Testing event correlation..."
curl -s -X POST "${API_BASE}/correlate" \
  -H "Content-Type: application/json" \
  -d '{
    "event_ids": ["event-123", "event-456"],
    "time_window": "5m",
    "max_distance": 3
  }' | jq '.'

# 14. Test fix application (dry run)
echo -e "\n14. Testing fix application (dry run)..."
curl -s -X POST "${API_BASE}/fixes/production/api-deployment/fix-memory/apply" \
  -H "Content-Type: application/json" \
  -d '{
    "dry_run": true,
    "force": false
  }' | jq '.'

echo -e "\n✅ API test completed!"
echo "The correlation engine is:"
echo "- Processing events from gRPC stream"
echo "- Generating insights stored in shared InsightStore"
echo "- Serving insights through REST API endpoints"