receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"
  
  # Prometheus receiver for scraping metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8889']

processors:
  # Batch processor for efficient export
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

  # Memory limiter to prevent OOM
  memory_limiter:
    limit_mib: 512

  # Resource processor to add standard attributes
  resource:
    attributes:
      - key: service.name
        value: tapio-correlation-engine
        action: upsert
      - key: service.version
        value: 1.0.0
        action: upsert
      - key: deployment.environment
        value: demo
        action: upsert

  # Attributes processor for Tapio-specific enrichment
  attributes:
    actions:
      - key: tapio.component
        action: upsert
        value: correlation-engine
      - key: tapio.export.timestamp
        action: upsert
        from_attribute: timestamp

  # Span processor for trace enhancement
  span:
    name:
      from_attributes: ["correlation.rule_name", "pattern.name"]
      separator: ":"

  # Transform processor for metric name normalization
  transform:
    metric_statements:
      - context: metric
        statements:
          - set(name, "tapio_" + name) where name !~ "^tapio_.*"

exporters:
  # Jaeger exporter for traces
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

  # Tempo exporter (alternative)
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  # Prometheus exporter for metrics
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      component: "tapio-otel-collector"
    
  # Prometheus remote write (if needed)
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
    tls:
      insecure: true

  # Loki exporter for logs
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    default_labels_enabled:
      exporter: false
      job: true

  # Debug exporter for troubleshooting
  debug:
    verbosity: basic

service:
  pipelines:
    # Traces pipeline
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource, attributes, span]
      exporters: [jaeger, otlp/tempo, debug]

    # Metrics pipeline
    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, batch, resource, attributes, transform]
      exporters: [prometheus, prometheusremotewrite]

    # Logs pipeline
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource, attributes]
      exporters: [loki, debug]

  extensions: [health_check, pprof, zpages]

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  
  pprof:
    endpoint: 0.0.0.0:1777
  
  zpages:
    endpoint: 0.0.0.0:55679