global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "tapio-alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Tapio correlation engine metrics
  - job_name: 'tapio-correlation'
    static_configs:
      - targets: ['tapio-demo:9091']
    scrape_interval: 10s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'tapio-correlation-engine'

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 15s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Jaeger metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    scrape_interval: 30s

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics
    scrape_interval: 30s

  # Tempo metrics
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
    metrics_path: /metrics
    scrape_interval: 30s

  # Custom Tapio pattern metrics
  - job_name: 'tapio-patterns'
    static_configs:
      - targets: ['tapio-demo:9091']
    scrape_interval: 5s
    metrics_path: /metrics
    params:
      collect: ['tapio_patterns']
    relabel_configs:
      - source_labels: [__name__]
        regex: 'tapio_patterns_.*'
        target_label: __tmp_keep
        replacement: 'true'
      - source_labels: [__tmp_keep]
        regex: 'true'
        action: keep

  # Tapio system health metrics
  - job_name: 'tapio-system-health'
    static_configs:
      - targets: ['tapio-demo:9091']
    scrape_interval: 15s
    metrics_path: /metrics
    params:
      collect: ['tapio_system']
    relabel_configs:
      - source_labels: [__name__]
        regex: 'tapio_system_.*'
        target_label: __tmp_keep
        replacement: 'true'
      - source_labels: [__tmp_keep]
        regex: 'true'
        action: keep

# Recording rules for Tapio metrics
rule_files:
  - "tapio-recording-rules.yml"