// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {time} from '../models';
import {http} from '../models';

export function ApplyFix(arg1:string,arg2:string):Promise<boolean>;

export function ConnectToServer(arg1:string):Promise<boolean>;

export function GetClusterStatus():Promise<main.ClusterStatus>;

export function GetHealth():Promise<main.HealthResponse>;

export function GetRealTimeData():Promise<Record<string, any>>;

export function GetServerInfo():Promise<Record<string, any>>;

export function GetStories():Promise<Array<main.Story>>;

export function GetTraceByID(arg1:string):Promise<main.OTELTrace>;

export function GetTraceTimeline(arg1:time.Time,arg2:time.Time):Promise<Array<main.OTELTrace>>;

export function GetTraces(arg1:string,arg2:number):Promise<Array<main.OTELTrace>>;

export function GetTracesForStory(arg1:string):Promise<Array<main.OTELTrace>>;

export function Greet(arg1:string):Promise<string>;

export function HandleWebSocket(arg1:main.WebSocketHub):Promise<http.HandlerFunc>;

export function LinkStoryToTrace(arg1:string,arg2:string):Promise<void>;

export function RefreshStories():Promise<boolean>;

export function StartDevServer(arg1:number):Promise<void>;

export function StartRealTimeUpdates(arg1:main.WebSocketHub):Promise<void>;

export function StopDevServer():Promise<void>;
