apiVersion: behavior.tapio.io/v1
kind: BehaviorPattern
metadata:
  name: config-drift
  version: "1.0.0"
  description: "Detects configuration changes that will cause pod failures"
spec:
  enabled: true
  priority: 90
  base_confidence: 0.75
  
  conditions:
    # ConfigMap or Secret was updated
    - type: event
      field: k8s_context.kind
      operator: in
      value: ["ConfigMap", "Secret"]
      required: true
      
    # Update event type
    - type: event
      field: type
      operator: equals
      value: "kubernetes"
      required: true
      
    # Check for update action
    - type: event
      field: attributes.action
      operator: in
      value: ["update", "patch", "replace"]
      required: false
      
  predictions:
    - type: failure
      confidence_base: 0.75
      time_horizon: "30m"
      message: "Pods mounting this configuration will restart and may fail within 30 minutes"
      severity: medium
      impact:
        - pod
        - service
        
  remediation:
    - priority: 1
      action: "Validate configuration syntax before rollout"
      command: "kubectl create --dry-run=client -f <config-file>"
      description: "Ensures configuration is valid"
      risk: "None - validation only"
      
    - priority: 2
      action: "Rollback configuration change"
      command: "kubectl rollout undo deployment <deployment>"
      description: "Reverts to previous working configuration"
      risk: "May lose intended configuration changes"
      
    - priority: 3
      action: "Implement gradual rollout"
      command: "kubectl rollout pause deployment <deployment>"
      description: "Pauses rollout to limit impact"
      risk: "Partial deployment state"