version: "1.0"
patterns:
  - id: blue-green-deployment-issue
    name: Blue-Green Deployment Issue
    category: deployment
    description: Detects problems during blue-green deployments
    enabled: true
    tags: ["deployment", "blue-green", "advanced"]
    indicators:
      - type: event
        field: reason
        condition: equals
        value: FailedCreate
      - type: state
        field: deployment.status.replicas
        condition: less_than
        value: deployment.spec.replicas
        time_window: 10m
      - type: event
        field: message
        condition: contains
        value: "insufficient resources"
    impact:
      severity: high
      scope: service
      user_impact: true
      performance_risk: false
    correlations:
      - rolling-update-failure
      - resource-exhaustion

  - id: canary-deployment-regression
    name: Canary Deployment Regression
    category: deployment
    description: Detects regressions in canary deployments
    enabled: true
    tags: ["deployment", "canary", "regression"]
    indicators:
      - type: metric
        field: error_rate
        condition: greater_than
        threshold: 0.05
        time_window: 5m
      - type: event
        field: labels.version
        condition: equals
        value: canary
      - type: metric
        field: latency_p99
        condition: greater_than
        threshold: 1000
    impact:
      severity: high
      scope: service
      user_impact: true
      performance_risk: true

  - id: deployment-quota-exceeded
    name: Deployment Quota Exceeded
    category: deployment
    description: Deployment blocked by resource quotas
    enabled: true
    tags: ["deployment", "quota", "resource"]
    indicators:
      - type: event
        field: reason
        condition: equals
        value: FailedCreate
      - type: event
        field: message
        condition: contains
        value: "exceeded quota"
    impact:
      severity: medium
      scope: namespace
      user_impact: false
      performance_risk: false