name: Architecture Compliance Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  architecture-check:
    name: Check Architecture Compliance
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Make scripts executable
      run: chmod +x scripts/migration/*.sh
      
    - name: Check dependency hierarchy
      run: |
        echo "🏗️ Checking Tapio architecture compliance..."
        ./scripts/migration/check-dependencies.sh
      
    - name: Check for circular dependencies
      run: |
        echo "🔄 Checking for circular dependencies..."
        # Simple check - will enhance later
        go mod graph | grep "github.com/falseyair/tapio" | sort | uniq > /tmp/deps.txt
        if grep -E "pkg/collectors.*pkg/collectors" /tmp/deps.txt; then
          echo "❌ Found collectors importing other collectors!"
          exit 1
        fi
        echo "✅ No obvious circular dependencies found"
        
    - name: Verify module isolation
      run: |
        echo "📦 Verifying module isolation..."
        for module in $(find pkg -name go.mod -type f | head -10); do
          dir=$(dirname $module)
          echo "Checking $dir..."
          cd $dir
          if ! go build ./...; then
            echo "❌ Module $dir failed to build independently"
            exit 1
          fi
          cd - > /dev/null
        done
        echo "✅ All modules build independently"

  architecture-report:
    name: Generate Architecture Report
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Generate import analysis
      run: |
        chmod +x scripts/migration/analyze-imports.sh
        ./scripts/migration/analyze-imports.sh || true
        
    - name: Comment on PR
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          let report = '## 🏗️ Architecture Analysis\n\n';
          report += 'This PR has been analyzed for architectural compliance.\n\n';
          report += '### Checks Performed:\n';
          report += '- ✅ Dependency hierarchy validation\n';
          report += '- ✅ Circular dependency detection\n';
          report += '- ✅ Module isolation verification\n';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: report
          });