name: Release

on:
  push:
    tags:
      - 'v*'

env:
  GO_VERSION: '1.24'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Install eBPF dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm libbpf-dev linux-headers-$(uname -r)
      
      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o tapio-linux-amd64 ./cmd/tapio
          GOOS=linux GOARCH=arm64 go build -o tapio-linux-arm64 ./cmd/tapio
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            tapio-linux-amd64
            tapio-linux-arm64
          generate_release_notes: true